### ISSUE TITLE
TCP/IP Network Administration

### ISSUE THREAD

**Issue by codeanit** [LearnWithAnit/learnwithanit.github.io#14]
- [x] Make course plan checklist
- [x] Create [repository](https://github.com/LearnWithAnit/tcp-ip-network-administration)
- [x] Resource: https://www.cs.ait.ac.th/~on/O/oreilly/tcpip/tcpip/index.htm

> Overview of chapters
Conceptually, this book is divided into three parts: fundamental concepts, tutorial, and reference. The first three chapters are a basic discussion of the TCP/IP protocols and services. This discussion provides the fundamental concepts necessary to understand the rest of the book. The remaining chapters provide a "how-to" tutorial. Chapters 4-7 discuss how to plan a network installation and configure the basic software necessary to get a network running. Chapters 8-10 discuss how to set up various important network services. The final chapters, 11-13, cover how to perform the ongoing tasks that are essential for a reliable network: troubleshooting, security, and keeping up with changing network information. The book concludes with a series of appendices that are technical references for important commands and programs.

> Chapters
- [ ] [Chapter 1: Overview of TCP/IP](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/1)
- [ ] [Chapter 2: Delivering the Data](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/2)
- [ ] [Chapter 3: Network Services](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/3)
- [ ] [Chapter 4: Getting Started](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/4)
- [ ] [Chapter 5: Basic Configuration](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/5)
- [ ] [Chapter 6: Configuring the Interface](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/6)
- [ ] [Chapter 7: Configuring Routing](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/7)
- [ ] [Chapter 8: Configuring DNS Name Service](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/8)
- [ ] [Chapter 9: Configuring Network Servers](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/9)
- [ ] [Chapter 10: sendmail](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/10)
- [ ] [Chapter 11: Troubleshooting TCP/IP](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/11)
- [ ] [Chapter 12: Network Security](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/12)
- [ ] [Chapter 13: Internet Information Resources](https://github.com/LearnWithAnit/tcp-ip-network-administration/issues/13)
